#! /bin/bash

# delete custom images

docker image rm -f custom/almalinux:9
docker image rm -f custom/almalinux:10

docker image rm -f custom/rockylinux:9
docker image rm -f custom/rockylinux:10

docker image rm -f custom/fedora:45
docker image rm -f custom/fedora:44
docker image rm -f custom/fedora:43

docker image rm -f custom/oraclelinux:9
docker image rm -f custom/oraclelinux:10

docker image rm -f custom/debian:12
docker image rm -f custom/debian:13

docker image rm -f custom/ubuntu:24.04
docker image rm -f custom/ubuntu:26.04




