#! /bin/bash

# delete build images for the specified package

#--------------------------------------------------------------------
# usage function
#

function usage() {
    echo
    echo "Delete build images for the specified package"
    echo "Usage:"
    echo "  $scriptName [options below]"
    echo "  -h   :  help"
    echo "  -d   :  turn debugging on"
    echo "  -p ? :  set lrose_pkg"
    echo "          e.g. core, blaze, cyclone, radx"
    echo
}

scriptName=$(basename $0)
lrose_pkg=lrose-core

# Parse command line options.
while getopts hdp: OPT; do
    case "$OPT" in
        h)
            usage
            exit 0
            ;;
        d)
            debug=true
            ;;
        p)
            lrose_pkg=$OPTARG
            ;;
        \?)
            # getopts issues an error message
            echo "Problems with command line usage"
            usage
            exit 1
            ;;
    esac
done

# delete build images

docker image rm -f build.${lrose_pkg}/almalinux:10
docker image rm -f build.${lrose_pkg}/almalinux:9

docker image rm -f build.${lrose_pkg}/rockylinux:10
docker image rm -f build.${lrose_pkg}/rockylinux:9

docker image rm -f build.${lrose_pkg}/oraclelinux:10
docker image rm -f build.${lrose_pkg}/oraclelinux:9

docker image rm -f build.${lrose_pkg}/fedora:45
docker image rm -f build.${lrose_pkg}/fedora:44
docker image rm -f build.${lrose_pkg}/fedora:43

docker image rm -f build.${lrose_pkg}/debian:latest
docker image rm -f build.${lrose_pkg}/debian:12

docker image rm -f build.${lrose_pkg}/ubuntu:26.04
docker image rm -f build.${lrose_pkg}/ubuntu:24.04

#docker image rm -f build.${lrose_pkg}/opensuse:leap
#docker image rm -f build.${lrose_pkg}/opensuse:latest
#docker image rm -f build.${lrose_pkg}/opensuse:15.6

