#! /bin/csh

# make custom images for the OSs

# ALMA LINUX

./redhat/make_custom_image.redhat -t almalinux -v 10
./redhat/make_custom_image.redhat -t almalinux -v 9

# ROCKY LINUX

./redhat/make_custom_image.redhat -t rockylinux -v 10
./redhat/make_custom_image.redhat -t rockylinux -v 9

# ORACLE

./oracle/make_custom_image.oracle -t oraclelinux -v 10
./oracle/make_custom_image.oracle -t oraclelinux -v 9

# FEDORA

./redhat/make_custom_image.redhat -t fedora -v 45
./redhat/make_custom_image.redhat -t fedora -v 44
./redhat/make_custom_image.redhat -t fedora -v 43

# DEBIAN

./debian/make_custom_image.debian -t debian -v 13
./debian/make_custom_image.debian -t debian -v 12

# UBUNTU

./debian/make_custom_image.debian -t ubuntu -v 26.04
./debian/make_custom_image.debian -t ubuntu -v 24.04

