package:
  name: lrose-core
  version: 20241008

source:
   git_url: https://github.com/NCAR/lrose-core.git
   git_rev: HEAD
   git_depth: -1
build:
  number: 0
  script: |
    mkdir build_dir
    {% if osx %}
    #  to find package OpenGL, need to specify path to OSX SDK 
      SDK_PATH=`xcrun --show-sdk-path`
      cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_OSX_SYSROOT=${SDK_PATH} -S . -B ./build_dir
    {% else %}
      cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DMAMBA_BUILD=1 -S . -B ./build_dir 
    {% endif %}
    cd build_dir
    make -j 8 install

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake
    {% if linux %}
    - libgcc
    {% endif %}
    {% if linux or osx %}
    - libcxx-devel
    {% endif %}
    - libpng
    - libtiff
    - libzip
    - zlib
    - bzip2
    - expat
    - libcurl
    - openmpi
    {% if linux or osx %}
    - flex
    {% elif win %}
    - winflexbison
    {% endif %}
    - fftw
    - hdf5
    - libnetcdf
    - xorg-libx11
    - xorg-libsm
    - xorg-libxext
    - xorg-libxpm
    - xorg-libxau
    - xorg-libxaw
    - xorg-xauth
    - xorg-libxt
    - xorg-xtrans
    - qt6-main
    - qt6-charts
    - qt6-graphs
    - qt6-3d
    - qt6-quick3d
    - qt6-datavis3d
    - qt6-multimedia
    {% if linux or win %}
    - xorg-font-util
    - xorg-xbitmaps
    - qt6-networkauth
    {% endif %}
    {% if linux %}
    - qt6-wayland
    - libgl-devel
    - libopengl-devel
    {% endif %}
    {% if osx %}
    - pyopengl
    - glfw
    {% endif %}
run:
    - numpy 1.26
    - libcxx
    - libpng
    - libtiff
    - libzip
    - zlib
    - bzip2
    - expat
    - libcurl
    - openmpi
    {% if linux or osx %}
    - flex
    {% elif win %}
    - winflexbison
    {% endif %}
    - fftw
    - hdf5
    - libnetcdf
    - xorg-libx11
    - xorg-libsm
    - xorg-libxext
    - xorg-libxpm
    - xorg-libxau
    - xorg-libxaw
    - xorg-xauth
    - xorg-libxt
    - xorg-xtrans
    - qt6-main
    - qt6-charts
    - qt6-graphs
    - qt6-3d
    - qt6-quick3d
    - qt6-datavis3d
    - qt6-multimedia
    {% if linux or win %}
    - xorg-font-util
    - xorg-xbitmaps
    - qt6-networkauth
    {% endif %}
    {% if linux %}
    - qt6-wayland
    - libgl-devel
    - libopengl-devel
    {% endif %}
    - libstdcxx-ng  # or other C++ runtime libraries

test:
  # List of commands to run after the build to validate it
  commands:
    - RadxPrint -h
    - RadxConvert -print_params
    - PrintMdv -h

  # Files that should be present after the build
  files:
    - bin/RadxPrint
    - lib/libtoolsa.so

about:
  home: http://lrose.net/
  license: BSD
  summary: 'LROSE: Lidar Radar Open Software Environment'
  description: |
     LROSE: Lidar Radar Open Software Environment
     LROSE is suppoted by the  National Science Foundation (NSF) for the Lidar, Radar, and Profiler community.
  dev_url: https://github.com/NCAR/lrose-core
  doc_url: http://wiki.lrose.net/index.php/Main_Page
  doc_source_url: http://wiki.lrose.net/index.php/Main_Page

