{% set version = "20230814" %}

package:
  name: my-core2
  # name: lrose-core
  version: {{ version }}

source:
  path: lrose-core 
  # url for Mac OSX
  # url: https://github.com/NCAR/lrose-core/releases/download/lrose-core-{{ version }}/lrose-core-{{ version }}.src.mac_osx.tgz
  
  # url for linux
  # url: https://github.com/NCAR/lrose-core/releases/download/lrose-core-{{ version }}/lrose-core-{{ version }}.src.tgz
  #sha256: f3832918bc3c66617f92e35f5d70729187676313caa60c187eb0f28b8fe5e3b5

build:
#  noarch: python
  number: 0
  #script: g++  hello_world.cc -o hello_world
  # script: build.sh


requirements:
  build:
    - gcc_linux-64
    - gxx_linux-64
    - gfortran_linux-64
    - make
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }} 
  host:
    - eigen
    - fftw
    - flex
    - qt
    # - mesa-libgl-devel-cos7-aarch64
    #- libglvnd-opengl-cos7-x86_64
    - libnetcdf
#    - szip
    - pkg-config
#    - geographiclib
#    - armadillo
#    - libomp
#    - libzip
#    - rsync
#    - xquartz
#    - {{ compiler('cxx') }}
  #host:
  #  - python
  #  - pip
  #run:
  #  - python

#test:
  #imports:
    #- imagesize

#about:
  #home: http://lrose.net/
  #license: LROSE BSD 
  #summary: 'LROSE: Lidar Radar Open Software Environment'
  #description: |
    # LROSE: Lidar Radar Open Software Environment
    # LROSE is suppoted by the  National Science Foundation (NSF) for the Lidar, Radar, and Profiler community.
  #dev_url: https://github.com/NCAR/lrose-core
  #doc_url: http://wiki.lrose.net/index.php/Main_Page
  #doc_source_url: http://wiki.lrose.net/index.php/Main_Page
