{% set version = "20230814" %}

package:
  name: my-core
  # name: lrose-core
  version: {{ version }}

source:
  path: ../src_test
  #url: https://github.com/NCAR/lrose-core/releases/download/lrose-core-{{ version }}/lrose-core-{{ version }}.src.tgz
  #sha256: f3832918bc3c66617f92e35f5d70729187676313caa60c187eb0f28b8fe5e3b5

build:
#  noarch: python
  number: 0
  #script: g++  hello_world.cc -o hello_world
  # script: build.sh

requirements:
  build:
  #  - cmake
    - {{ compiler('cxx') }}
  #host:
  #  - python
  #  - pip
  #run:
  #  - python

test:
  #imports:
    #- imagesize

#about:
  #home: https://github.com/shibukawa/imagesize_py
  #license: MIT
  #summary: 'Getting image size from png/jpeg/jpeg2000/gif file'
  #description: |
    #This module analyzes jpeg/jpeg2000/png/gif image header and
    #return image size.
  #dev_url: https://github.com/shibukawa/imagesize_py
  #doc_url: https://pypi.python.org/pypi/imagesize
  #doc_source_url: https://github.com/shibukawa/imagesize_py/blob/master/README.rst
