#! /bin/csh

mkdir /tmp/singularity

cd ~/git/lrose-bootstrap/singularity

sudo singularity build -F /tmp/singularity/custom.centos.8.sif custom.centos.8.def

sudo singularity build -F /tmp/singularity/lrose_build.sif lrose_build.def

