#! /bin/bash

# compilers etc.

mamba install -y --channel conda-forge cmake gcc cxx-compiler libcxx-devel

# compression, images, xml etc

mamba install -y --channel conda-forge libpng libtiff libzip zlib bzip2
mamba install -y --channel conda-forge expat libcurl openmpi
mamba install -y --channel conda-forge flex fftw

# netcdf

mamba install -y --channel conda-forge hdf5 libnetcdf

# X11

mamba install -y --channel conda-forge xorg-libx11 xorg-libxext
mamba install -y --channel conda-forge libx11-devel libx11-common

# qt6

mamba install -y --channel conda-forge qt6-main qt6-networkauth
mamba install -y --channel conda-forge qt6-charts qt6-graphs qt6-wayland
mamba install -y --channel conda-forge qt6-3d qt6-quick3d qt6-datavis3d
mamba install -y --channel conda-forge qt6-multimedia

# gl support for qt6

mamba install -y --channel conda-forge libgl-devel libopengl-devel

