#! /bin/bash

# go to mamba dir

cd ~/git/mamba

# build

mamba install -y --channel conda-forge cmake gcc libcxx-devel

# compression etc

mamba install -y --channel conda-forge libpng libtiff libzip zlib bzip2
mamba install -y --channel conda-forge expat libcurl openmpi
mamba install -y --channel conda-forge flex fftw

# netcdf

mamba install -y --channel conda-forge hdf5 libnetcdf

# X11

mamba install -y --channel conda-forge xorg-libx11 xorg-libxext
mamba install -y --channel conda-forge libx11-devel libx11-common

# qt6

mamba install -y --channel conda-forge qt6-main qt6-networkauth
mamba install -y --channel conda-forge qt6-charts qt6-graphs qt6-wayland
mamba install -y --channel conda-forge qt6-3d qt6-datavis3d
