#! /bin/bash

# compilers etc.

~/mambaforge/bin/mamba install -y --channel conda-forge cmake gcc cxx-compiler libcxx-devel

# compression, images, xml etc

~/mambaforge/bin/mamba install -y --channel conda-forge libpng libtiff libzip zlib bzip2
~/mambaforge/bin/mamba install -y --channel conda-forge expat libcurl openmpi
~/mambaforge/bin/mamba install -y --channel conda-forge flex fftw

# netcdf

~/mambaforge/bin/mamba install -y --channel conda-forge hdf5 libnetcdf

# X11

~/mambaforge/bin/mamba install -y --channel conda-forge xorg-libx11 xorg-libxext
~/mambaforge/bin/mamba install -y --channel conda-forge libx11-devel libx11-common

# qt6

~/mambaforge/bin/mamba install -y --channel conda-forge qt6-main qt6-networkauth
~/mambaforge/bin/mamba install -y --channel conda-forge qt6-charts qt6-graphs qt6-wayland
~/mambaforge/bin/mamba install -y --channel conda-forge qt6-3d qt6-quick3d qt6-datavis3d
~/mambaforge/bin/mamba install -y --channel conda-forge qt6-multimedia

# gl support for qt6

~/mambaforge/bin/mamba install -y --channel conda-forge libgl-devel libopengl-devel

